# Generated by Django 4.1.3 on 2022-11-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disease', '0001_initial'),
        ('Country', '0001_initial'),
        ('PublicServant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='Country.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='Disease.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='PublicServant.publicservant')),
            ],
            options={
                'unique_together': {('email', 'cname', 'disease_code')},
            },
        ),
    ]
